version: '3.8'

services:
  nginx:
    container_name: dev_tasktracker_nginx
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf
    depends_on:
      - rustapp

  rustapp:
    container_name: dev_tasktracker_rustapp
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/backend
      - /usr/src/backend/target
    environment:
      DATABASE_URL: postgres://tasktracker_user:tasktracker_password@postgres:5432
      # DATABASE_URL: postgres://tasktracker_user:tasktracker_password@postgres:5432/tasktracker_db
    depends_on:
      - postgres

  postgres:
    container_name: dev_tasktracker_postgres
    # image: postgres
    image: postgis/postgis:16-3.5
    environment:
      POSTGRES_USER: tasktracker_user
      POSTGRES_PASSWORD: tasktracker_password
      POSTGRES_DB: tasktracker_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
