version: '3.8'

services:
  backend:
    container_name: dev_ayohf_backend
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8080:8080"
  nginx:
    container_name: dev_ayohf_nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
  db:
    container_name: dev_ayohf_db
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
