# Development environment
FROM rust:slim-bookworm
# FROM rust:latest

# Install dependencies
RUN apt-get update && apt-get install -y \
    libssl-dev \
    libpq-dev \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*

# Install cargo-watch
RUN cargo install cargo-watch

WORKDIR /usr/src/backend

# Cache dependencies
COPY Cargo.toml Cargo.lock ./
RUN cargo fetch

# Copy source code
COPY . .

# Set environment variables
ENV PORT 8080

# Expose the application's port
EXPOSE $PORT

# Command to run the application with cargo watch
CMD ["cargo", "watch", "-x", "run"]
