FROM rust:latest

# Install dependencies
RUN apt-get update && apt-get install -y libpq-dev

# Install cargo-watch
RUN cargo install cargo-watch

WORKDIR /usr/src/backend

# Cache dependencies
COPY Cargo.toml Cargo.lock ./
RUN cargo fetch

# Copy source code
COPY . .
COPY .env .env
COPY .env.test .env.test

ENV PORT 8080

EXPOSE $PORT

CMD ["cargo", "watch", "-x", "run"]
# CMD ["cargo", "run"]
# CMD ["dev", "cargo", "run"]
