FROM rust:latest AS builder
WORKDIR /usr/src/backend
COPY . .
RUN cargo build --release

FROM debian:buster-slim
COPY --from=builder /usr/src/backend/target/release/backend /usr/local/bin/backend
CMD ["backend"]
