version: '3.8'

services:
  nginx:
    container_name: prod_tasktracker_nginx
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf
    depends_on:
      - rustapp

  rustapp:
    container_name: prod_tasktracker_rustapp
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/backend
      - /usr/src/backend/target
    depends_on:
      - postgres

  postgres:
    container_name: prod_tasktracker_postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
